### PR TITLE
feat(SR payin update): Update audience images and style audience page

### PR DESCRIPTION
**Pull request by lebaz20**
fix comicrelief/payin#369

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
@lebaz20: just in case it's still an issue, I was having problems with semvar on the last release, and ending up just having to `yarn publish` locally in order to release to npm

**Comment by lebaz20** [comment]
@AndyEPhipps Yeah as you can see concourse-ci/status is waiting forever, and i don't think we have a pipeline on concourse for PL! 
But I don't think I have enough permissions to do so.

**Comment by AndyEPhipps** [comment]
> @AndyEPhipps Yeah as you can see concourse-ci/status is waiting forever, and i don't think we have a pipeline on concourse for PL!
> But I don't think I have enough permissions to do so.

Ah yeah, that is a problem. Maybe it's a pipeline that got forgotten during @adamclark-dev 's semi-recent overhaul?

For now, I can just admin merge this in for you and release it via command line, once you're ready

**Comment by lebaz20** [comment]
@AndyEPhipps Ok that would be awesome, and I think it is ready now to be merged!
Thanks!

**Pull request merged**
