### PR TITLE
feat: Refactoring for better overriding

### PR DESCRIPTION
**Pull request by gusliedke**
BREAKING CHANGE: Adding new sass structure for all sub products spliting var and core

### CODE REVIEW

**Comment by gusliedke** [comment]
@ayanozturk @KoalaMango If this change won't break any prod environments can we please merge it. Our campaign integration is waiting for this PR to work.

**Comment by NoelLH** [comment]
@gusliedke If the PR contains breaking changes we need a commit message that has the `BREAKING CHANGE` in the right place - putting on the GitHub PR won't do anything.

`npm run commit` lets you build the message interactively.

**Comment by gusliedke** [comment]
@NoelLH I did .. I put this message in my commit and it showed up here in github title and description

**Comment by NoelLH** [comment]
Sorry @gusliedke, pesky GitHub hiding multi line messages!

**Pull request merged**
