### PR TITLE
New SR theme stuff

### PR DESCRIPTION
**Pull request by AndyEPhipps**
#896

### CODE REVIEW

**Comment by AndyEPhipps** [comment]
Hey guys, here's the WIP theme update that I've been working on with `young Mr Squire`; it's all just font stuff currently.

We'll need to add-in new colours variables, bg-colour classes, tweak button styles, add in 2-card View mode styles (dead easy).

**Comment by AndyEPhipps** [comment]
Taggin' @JamesSquire

**Comment by JamesSquire** [comment]
Hey! I believe Andy's done most of the font work. May need to have a look within a test environment to check it all works okay as we're only updating fonts and not sizing so it may or may not be a seamless transition. 

bg-colour classes should be: Light Blue - #86E4E9, Coral - #FF6F61, Dark Blue, #3A4972, CR Red - #E52630. We're adding rather than replacing so not to interfere with current content. I believe "Dark Blue" already exists as a name however, so perhaps new colours should have a SR19 prefix (e.g. "SR19 - Dark Blue", "SR19 - Coral", etc.)

These colours need to be made into variables(?) too, so that we can make text these colours (so how "font--red" etc. works currently). Happy for them to be added as block style options within the WYSIWYG but, in the interest of speed, I'm absolutely fine to manually add the classes if needs be.

Buttons to follow!

**Comment by JamesSquire** [comment]
Buttons! Keeping these relatively simple for now. As before, we're adding and not updating existing styles. They retain the shape, font size and padding as the current buttons, however. Font is Montserrat Black and, unlike the current buttons, no letter-spacing is required. Hover state has also been kept simple, with no movement or transitions. See the attached image for a reference, and lemme know if you have any questions. 

buttons

Again, like the colours, names may already exist so I suggest adding a prefix. In order of appearance, I prepose 'SR19 - Light-blue button', 'SR19 - Black button', 'SR19 - White button'.

**Comment by LouiaR** [comment]
Hey @JamesSquire  for the btn with background light blue do you mean #86E4E9 instead of #3A4972

**Pull request merged**
