### PR TITLE
feat: new scenarios

### LINKED ISSUE #102: PL-21 ⁃ Update more test scenarios
Update more test scenarios in backstop.json

### PR DESCRIPTION
**Pull request by gusliedke**
fixes #102

### CODE REVIEW

**Comment by gusliedke** [comment]
You can see new tests [here](https://deploy-preview-142--pattern-lab-visual-regression.netlify.com/html_report/) . but test env doesn't look like the screenshots.

**Comment by AndyEPhipps** [comment]
@gusliedke - is this still in progress?

**Comment by gusliedke** [comment]
@AndyEPhipps I'm fine to get it merged .. as I mentioned some screenshots don't match with the environment but is better than our current visual regression which is not useful

**Comment by gusliedke** [comment]
Would be good to try chromy as our headless browser engine instead casper or phantom

**Pull request closed without merging**
